import { NextRequest, NextResponse } from 'next/server'

// Google Calendar API endpoint
const GOOGLE_CALENDAR_API = 'https://www.googleapis.com/calendar/v3'

export async function POST(request: NextRequest) {
  try {
    const { accessToken, events, timezone } = await request.json()

    console.log('📅 Google Calendar API called with', events?.length, 'events')

    if (!accessToken) {
      console.error('❌ No access token provided')
      return NextResponse.json({ error: 'Access token required' }, { status: 401 })
    }

    if (!events || !Array.isArray(events)) {
      console.error('❌ No events array provided')
      return NextResponse.json({ error: 'Events array required' }, { status: 400 })
    }

    const userTimezone = timezone || 'Asia/Kolkata'
    const results = []
    
    for (const event of events) {
      const startDate = new Date(event.date)
      startDate.setHours(9, 0, 0, 0) // Default 9 AM
      const endDate = new Date(startDate)
      endDate.setMinutes(endDate.getMinutes() + (event.duration || 60))

      const calendarEvent = {
        summary: `📚 Study Day ${event.day}: ${event.topics.join(', ')}`,
        description: `Study Session - Day ${event.day}\n\nTopics:\n${event.topics.map((t: string, i: number) => `${i + 1}. ${t}`).join('\n')}\n\nDuration: ${event.duration} minutes\nPriority: ${event.priority}\n\n📝 Generated by NoteGenie`,
        start: {
          dateTime: startDate.toISOString(),
          timeZone: userTimezone,
        },
        end: {
          dateTime: endDate.toISOString(),
          timeZone: userTimezone,
        },
        reminders: {
          useDefault: false,
          overrides: [
            { method: 'popup', minutes: 30 },
          ],
        },
        colorId: event.priority === 'high' ? '11' : event.priority === 'medium' ? '5' : '9',
      }

      console.log('📆 Adding event for Day', event.day)

      try {
        const response = await fetch(`${GOOGLE_CALENDAR_API}/calendars/primary/events`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(calendarEvent),
        })

        const data = await response.json()
        
        if (response.ok) {
          console.log('✅ Event added:', data.id)
          results.push({ day: event.day, success: true, eventId: data.id })
        } else {
          console.error('❌ Failed to add event:', data.error?.message)
          results.push({ day: event.day, success: false, error: data.error?.message || 'Failed' })
        }
      } catch (err: any) {
        console.error('❌ Network error:', err.message)
        results.push({ day: event.day, success: false, error: 'Network error' })
      }
    }

    const successCount = results.filter(r => r.success).length
    console.log(`📊 Results: ${successCount}/${events.length} events added`)
    
    return NextResponse.json({ 
      success: successCount > 0, 
      message: `Added ${successCount}/${events.length} events to Google Calendar`,
      results 
    })

  } catch (error) {
    console.error('Google Calendar API error:', error)
    return NextResponse.json({ error: 'Failed to add events' }, { status: 500 })
  }
}
