'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import PageLayout from '@/components/layout/PageLayout'
import Card from '@/components/ui/Card'
import Button from '@/components/ui/Button'
import { useApp } from '@/context/AppContext'
import { createStudyPlan } from '@/agents/studyPlanAgent'

// Local storage key for study plan
const STUDY_PLAN_CACHE_KEY = 'notegenie_study_plan'

// Save plan to localStorage
const savePlanToLocal = (userId: string, plan: any[]) => {
  if (typeof window === 'undefined') return
  try {
    localStorage.setItem(`${STUDY_PLAN_CACHE_KEY}_${userId}`, JSON.stringify(plan))
  } catch (e) {
    console.error('Error saving plan:', e)
  }
}

// Load plan from localStorage
const loadPlanFromLocal = (userId: string): any[] => {
  if (typeof window === 'undefined') return []
  try {
    const saved = localStorage.getItem(`${STUDY_PLAN_CACHE_KEY}_${userId}`)
    return saved ? JSON.parse(saved) : []
  } catch {
    return []
  }
}

// Google Calendar API helper - Format date for Google Calendar
const formatGoogleCalendarDate = (date: Date) => {
  return date.toISOString().replace(/-|:|\.\d{3}/g, '').slice(0, -1)
}

// Add single task to Google Calendar
const addToGoogleCalendar = (task: any) => {
  const startDate = new Date(task.date)
  startDate.setHours(9, 0, 0, 0) // Default 9 AM
  const endDate = new Date(startDate)
  endDate.setMinutes(endDate.getMinutes() + task.duration)

  const event = {
    text: `📚 Study: ${task.topics.join(', ')}`,
    dates: `${formatGoogleCalendarDate(startDate)}/${formatGoogleCalendarDate(endDate)}`,
    details: `Study Session - Day ${task.day}\n\nTopics: ${task.topics.join(', ')}\nDuration: ${task.duration} minutes\nPriority: ${task.priority}\n\nGenerated by NoteGenie 📝`,
  }

  const calendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.text)}&dates=${event.dates}&details=${encodeURIComponent(event.details)}`
  
  window.open(calendarUrl, '_blank')
}

// Generate ICS file for all tasks (downloads as .ics file that can be imported)
const downloadICSFile = (tasks: any[]) => {
  let icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//NoteGenie//Study Plan//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
`

  tasks.forEach(task => {
    const startDate = new Date(task.date)
    startDate.setHours(9, 0, 0, 0)
    const endDate = new Date(startDate)
    endDate.setMinutes(endDate.getMinutes() + task.duration)

    const formatICSDate = (d: Date) => d.toISOString().replace(/-|:|\.\d{3}/g, '').slice(0, -1) + 'Z'

    icsContent += `BEGIN:VEVENT
DTSTART:${formatICSDate(startDate)}
DTEND:${formatICSDate(endDate)}
SUMMARY:📚 Study Day ${task.day}: ${task.topics.join(', ')}
DESCRIPTION:Study Session - Day ${task.day}\\n\\nTopics: ${task.topics.join(', ')}\\nDuration: ${task.duration} minutes\\nPriority: ${task.priority}\\n\\nGenerated by NoteGenie
STATUS:CONFIRMED
END:VEVENT
`
  })

  icsContent += 'END:VCALENDAR'

  // Download the file
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = 'study-plan.ics'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export default function StudyPlanPage() {
  const router = useRouter()
  const { state, isReady, setStudyPlan, updateStudyTask, refreshData } = useApp()
  const [topics, setTopics] = useState('')
  const [timePerDay, setTimePerDay] = useState('60')
  const [daysUntilExam, setDaysUntilExam] = useState('14')
  const [generating, setGenerating] = useState(false)
  const [showFromNotes, setShowFromNotes] = useState(false)
  const [selectedConcepts, setSelectedConcepts] = useState<string[]>([])
  const [localPlan, setLocalPlan] = useState<any[]>([])
  const [addingToCalendar, setAddingToCalendar] = useState(false)
  const [studyMode, setStudyMode] = useState(false)
  const [currentStudyDay, setCurrentStudyDay] = useState<number>(1)
  
  // New study mode states
  const [studyContent, setStudyContent] = useState<any>(null)
  const [loadingContent, setLoadingContent] = useState(false)
  const [studyPhase, setStudyPhase] = useState<'reading' | 'quiz' | 'complete'>('reading')
  const [currentTopicIndex, setCurrentTopicIndex] = useState(0)
  const [quizAnswers, setQuizAnswers] = useState<number[]>([])
  const [showQuizResults, setShowQuizResults] = useState(false)
  const [quizScore, setQuizScore] = useState(0)
  
  // Google Calendar status
  const [calendarStatus, setCalendarStatus] = useState<'idle' | 'adding' | 'done'>('idle')

  // Load plan from localStorage on mount
  useEffect(() => {
    if (isReady && state.user) {
      const savedPlan = loadPlanFromLocal(state.user.id)
      if (savedPlan.length > 0 && state.studyPlan.length === 0) {
        setLocalPlan(savedPlan)
      }
    }
  }, [isReady, state.user, state.studyPlan.length])

  // Redirect to login if not authenticated (only after ready)
  useEffect(() => {
    if (isReady && !state.user) {
      router.push('/auth/login')
    }
  }, [isReady, state.user, router])

  // Extract unique concepts from user's notes
  const availableConcepts = state.concepts.map(c => c.term)
  const uniqueConcepts = [...new Set(availableConcepts)]
  
  // Use local plan if available, otherwise use state plan
  const displayPlan = localPlan.length > 0 ? localPlan : state.studyPlan

  // Find the current day to study (first incomplete day)
  const getCurrentStudyDay = () => {
    const incomplete = displayPlan.find(t => !t.completed)
    return incomplete ? incomplete.day : null
  }

  const handleToggleConcept = (concept: string) => {
    setSelectedConcepts(prev => 
      prev.includes(concept) 
        ? prev.filter(c => c !== concept)
        : [...prev, concept]
    )
  }

  const handleUseSelectedConcepts = () => {
    setTopics(selectedConcepts.join(', '))
    setShowFromNotes(false)
  }

  // Redirect to login if not authenticated (only after ready)
  useEffect(() => {
    if (isReady && !state.user) {
      router.push('/auth/login')
    }
  }, [isReady, state.user, router])

  if (!isReady) {
    return (
      <PageLayout>
        <div className="loading-state">
          <div className="loading-spinner"></div>
          <p>Loading study plan...</p>
          <style jsx>{`
            .loading-state {
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              min-height: 400px;
              gap: 20px;
              font-family: var(--font-body);
            }
            .loading-spinner {
              width: 50px;
              height: 50px;
              border: 4px solid #f3f3f3;
              border-top: 4px solid #000;
              border-radius: 50%;
              animation: spin 1s linear infinite;
            }
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          `}</style>
        </div>
      </PageLayout>
    )
  }

  // Toggle task completion
  const handleToggleComplete = async (taskId: string, currentCompleted: boolean) => {
    // Update local state immediately for responsiveness
    const newPlan = localPlan.map(t => 
      t.id === taskId ? { ...t, completed: !currentCompleted } : t
    )
    setLocalPlan(newPlan)
    
    // Save to localStorage for persistence
    if (state.user) {
      savePlanToLocal(state.user.id, newPlan)
    }
    
    // Update in database
    await updateStudyTask(taskId, { completed: !currentCompleted })
  }

  // Add all tasks to Google Calendar
  const handleAddAllToCalendar = () => {
    setAddingToCalendar(true)
    const tasksToAdd = displayPlan.filter(t => !t.completed)
    
    if (tasksToAdd.length === 0) {
      alert('All tasks are completed! 🎉')
      setAddingToCalendar(false)
      return
    }

    // Show confirmation - use ICS download for multiple events
    if (confirm(`Add ${tasksToAdd.length} study sessions to Google Calendar?\n\nThis will download an .ics file that you can import into Google Calendar to add all events at once.`)) {
      downloadICSFile(tasksToAdd)
      alert(`📅 Calendar file downloaded! Import "study-plan.ics" into Google Calendar:\n\n1. Open Google Calendar\n2. Click the gear icon → Settings\n3. Import & Export → Import\n4. Select the downloaded file`)
    }
    setAddingToCalendar(false)
  }

  // Open Google Calendar and add events one by one
  const handleAutoSyncToCalendar = async () => {
    const tasksToAdd = displayPlan.filter(t => !t.completed)
    
    if (tasksToAdd.length === 0) {
      alert('All tasks are completed! 🎉')
      return
    }

    setCalendarStatus('adding')
    
    // Confirm before opening multiple tabs
    const confirmed = confirm(
      `📅 Add ${tasksToAdd.length} study sessions to Google Calendar?\n\n` +
      `This will open Google Calendar ${tasksToAdd.length} times to add each event.\n` +
      `Please allow pop-ups if prompted.`
    )
    
    if (!confirmed) {
      setCalendarStatus('idle')
      return
    }

    // Open Google Calendar for each event with a delay
    let addedCount = 0
    
    for (let i = 0; i < tasksToAdd.length; i++) {
      const task = tasksToAdd[i]
      
      const startDate = new Date(task.date)
      startDate.setHours(9, 0, 0, 0)
      const endDate = new Date(startDate)
      endDate.setMinutes(endDate.getMinutes() + task.duration)

      const event = {
        text: `📚 Study Day ${task.day}: ${task.topics.join(', ')}`,
        dates: `${formatGoogleCalendarDate(startDate)}/${formatGoogleCalendarDate(endDate)}`,
        details: `Study Session - Day ${task.day}\n\nTopics:\n${task.topics.map((t: string, idx: number) => `${idx + 1}. ${t}`).join('\n')}\n\nDuration: ${task.duration} minutes\nPriority: ${task.priority}\n\n📝 Generated by NoteGenie`,
      }

      const calendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.text)}&dates=${event.dates}&details=${encodeURIComponent(event.details)}`
      
      // Open in new tab
      window.open(calendarUrl, `_blank`)
      addedCount++
      
      // Small delay between opening tabs to prevent browser blocking
      if (i < tasksToAdd.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 500))
      }
    }
    
    setCalendarStatus('done')
    alert(`✅ Opened ${addedCount} Google Calendar tabs!\n\nClick "Save" on each tab to add the events to your calendar.`)
  }

  // Download ICS file for all calendar events
  const handleDownloadCalendar = () => {
    const tasksToAdd = displayPlan.filter(t => !t.completed)
    if (tasksToAdd.length === 0) {
      alert('All tasks are completed! 🎉')
      return
    }
    downloadICSFile(tasksToAdd)
    alert(`📅 Calendar file downloaded! Import "study-plan.ics" into Google Calendar or any calendar app to add all ${tasksToAdd.length} study sessions.`)
  }

  // Load study content for current day
  const loadStudyContent = async (day: number) => {
    const task = displayPlan.find(t => t.day === day)
    if (!task) return
    
    setLoadingContent(true)
    setStudyContent(null)
    setStudyPhase('reading')
    setCurrentTopicIndex(0)
    setQuizAnswers([])
    setShowQuizResults(false)
    
    try {
      const response = await fetch('/api/study-content', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topics: task.topics,
          day: day
        })
      })
      
      const result = await response.json()
      
      if (result.success) {
        setStudyContent(result.content)
      } else {
        throw new Error(result.error)
      }
    } catch (error) {
      console.error('Failed to load study content:', error)
      // Create fallback content
      setStudyContent({
        topics: task.topics.map((topic: string) => ({
          name: topic,
          explanation: `Today we'll study ${topic}. Focus on understanding the core concepts and practice with examples.`,
          keyPoints: [`Understand ${topic} fundamentals`, `Practice regularly`, `Review key concepts`],
          examples: [`Real-world application of ${topic}`]
        })),
        mcqs: [
          {
            question: 'What is the most important aspect of studying?',
            options: ['Understanding concepts', 'Memorizing facts', 'Skipping exercises', 'Avoiding revision'],
            correctAnswer: 0,
            explanation: 'Understanding concepts is key to long-term retention.'
          },
          {
            question: 'How should you approach difficult topics?',
            options: ['Skip them', 'Practice more', 'Ignore them', 'Give up'],
            correctAnswer: 1,
            explanation: 'Practice makes perfect, especially for difficult topics.'
          },
          {
            question: 'What helps in retaining knowledge?',
            options: ['One-time reading', 'Regular revision', 'No practice', 'Passive reading'],
            correctAnswer: 1,
            explanation: 'Regular revision strengthens memory pathways.'
          }
        ]
      })
    } finally {
      setLoadingContent(false)
    }
  }

  // Start study mode for a specific day
  const handleStartStudy = async (day: number) => {
    setCurrentStudyDay(day)
    setStudyMode(true)
    await loadStudyContent(day)
  }

  // Handle quiz answer selection
  const handleQuizAnswer = (questionIndex: number, answerIndex: number) => {
    const newAnswers = [...quizAnswers]
    newAnswers[questionIndex] = answerIndex
    setQuizAnswers(newAnswers)
  }

  // Submit quiz and show results
  const handleSubmitQuiz = () => {
    if (!studyContent?.mcqs) return
    
    let score = 0
    studyContent.mcqs.forEach((mcq: any, idx: number) => {
      if (quizAnswers[idx] === mcq.correctAnswer) {
        score++
      }
    })
    
    setQuizScore(score)
    setShowQuizResults(true)
    
    // If all correct, allow completion
    if (score === studyContent.mcqs.length) {
      setStudyPhase('complete')
    }
  }

  // Complete current day after quiz
  const handleCompleteDay = async (taskId: string) => {
    // Mark as completed
    const updatedPlan = displayPlan.map(t => 
      t.id === taskId ? { ...t, completed: true } : t
    )
    setLocalPlan(updatedPlan)
    
    // Save to localStorage
    if (state.user) {
      savePlanToLocal(state.user.id, updatedPlan)
    }
    
    // Update in database
    await updateStudyTask(taskId, { completed: true })
    
    // Reset study mode state
    setStudyMode(false)
    setStudyContent(null)
    setStudyPhase('reading')
    setCurrentTopicIndex(0)
    setQuizAnswers([])
    setShowQuizResults(false)
    setCurrentStudyDay(1)
  }

  const handleGenerate = async () => {
    const topicsList = topics.split(',').map(t => t.trim()).filter(t => t)
    if (topicsList.length === 0) return

    setGenerating(true)
    try {
      console.log('📚 Generating study plan for:', topicsList)
      const planResult = await createStudyPlan({
        topics: topicsList,
        timePerDay: parseInt(timePerDay),
        daysUntilExam: parseInt(daysUntilExam),
      })
      console.log('✅ Plan result:', planResult)
      
      if (planResult.plan && planResult.plan.length > 0) {
        // Set local state immediately for display
        setLocalPlan(planResult.plan)
        
        // Save to localStorage for persistence
        if (state.user) {
          savePlanToLocal(state.user.id, planResult.plan)
        }
        
        // Save to DB
        await setStudyPlan(planResult.plan)
        console.log('💾 Plan saved to state and localStorage')
        // Refresh to ensure we have latest data
        await refreshData()
      } else {
        console.error('❌ Empty plan returned')
        alert('Could not generate study plan. Please try again.')
      }
    } catch (error) {
      console.error('Error generating study plan:', error)
      alert('Error generating study plan. Please try again.')
    } finally {
      setGenerating(false)
    }
  }

  // Get current task for study mode
  const currentTask = displayPlan.find(t => t.day === currentStudyDay)

  // Check if all tasks are completed
  const allCompleted = displayPlan.length > 0 && displayPlan.every(t => t.completed)

  return (
    <PageLayout>
      <div className="study-plan-page">
        {/* Study Mode - Full screen study experience */}
        {studyMode && currentTask && (
          <div className="study-mode-overlay">
            <div className="study-mode-container">
              <div className="study-mode-header">
                <span className="study-day-badge">📚 Day {currentTask.day}</span>
                <button className="close-study-btn" onClick={() => setStudyMode(false)}>✕</button>
              </div>
              
              <h2 className="study-title">Today's Study Session</h2>
              <p className="study-duration">⏱️ {currentTask.duration} minutes</p>
              
              <div className="study-topics-list">
                <h3>📖 Topics to Cover:</h3>
                {currentTask.topics.map((topic: string, idx: number) => (
                  <div key={idx} className="study-topic-item">
                    <span className="topic-number">{idx + 1}</span>
                    <span className="topic-name">{topic}</span>
                  </div>
                ))}
              </div>

              <div className="study-tips">
                <h4>💡 Study Tips:</h4>
                <ul>
                  <li>Find a quiet place to study</li>
                  <li>Remove distractions (phone, social media)</li>
                  <li>Take short breaks every 25 minutes</li>
                  <li>Make notes as you study</li>
                  <li>Try to explain concepts in your own words</li>
                </ul>
              </div>

              <div className="study-timer-section">
                <p>Set a timer for <strong>{currentTask.duration} minutes</strong> and start studying!</p>
              </div>

              <div className="study-actions">
                <Button 
                  onClick={() => handleCompleteDay(currentTask.id)}
                  className="complete-day-btn"
                >
                  ✅ Mark Day {currentTask.day} as Completed
                </Button>
              </div>

              {currentTask.day < displayPlan.length && (
                <p className="next-day-hint">
                  🌅 Come back tomorrow for Day {currentTask.day + 1}!
                </p>
              )}
            </div>
          </div>
        )}

        {/* Celebration when all done */}
        {allCompleted && displayPlan.length > 0 && (
          <div className="celebration-banner">
            <h2>🎉 Congratulations! You've completed your entire study plan!</h2>
            <p>You're ready for your exam! Good luck! 🍀</p>
          </div>
        )}

        <h1 className="page-title">📅 Study Plan & Progress</h1>
        <p className="page-subtitle">Create a personalized study schedule based on your topics and available time</p>

        {/* Input Form */}
        <Card>
          <h2 className="section-title">🎯 Generate Study Plan</h2>
          
          <div className="form-group">
            <label>Topics (comma-separated):</label>
            <div className="topic-input-wrapper">
              <input
                type="text"
                className="input"
                placeholder="e.g. Machine Learning, Neural Networks, Python"
                value={topics}
                onChange={(e) => setTopics(e.target.value)}
              />
              {uniqueConcepts.length > 0 && (
                <button 
                  className="from-notes-btn"
                  onClick={() => setShowFromNotes(!showFromNotes)}
                >
                  📚 From Notes
                </button>
              )}
            </div>
          </div>

          {/* Concepts from Notes */}
          {showFromNotes && uniqueConcepts.length > 0 && (
            <div className="concepts-picker">
              <p className="picker-label">Select concepts from your notes:</p>
              <div className="concepts-grid">
                {uniqueConcepts.slice(0, 20).map((concept, idx) => (
                  <button
                    key={idx}
                    className={`concept-chip ${selectedConcepts.includes(concept) ? 'selected' : ''}`}
                    onClick={() => handleToggleConcept(concept)}
                  >
                    {concept}
                  </button>
                ))}
              </div>
              {selectedConcepts.length > 0 && (
                <Button onClick={handleUseSelectedConcepts} size="sm">
                  Use {selectedConcepts.length} Selected Topics
                </Button>
              )}
            </div>
          )}

          <div className="form-row">
            <div className="form-group">
              <label>⏰ Study Time Per Day (minutes):</label>
              <input
                type="number"
                className="input"
                value={timePerDay}
                onChange={(e) => setTimePerDay(e.target.value)}
                min="30"
                max="480"
              />
            </div>

            <div className="form-group">
              <label>Days Until Exam:</label>
              <input
                type="number"
                className="input"
                value={daysUntilExam}
                onChange={(e) => setDaysUntilExam(e.target.value)}
                min="1"
                max="365"
              />
            </div>
          </div>

          <Button onClick={handleGenerate} disabled={!topics.trim() || generating} loading={generating}>
            {generating ? 'Generating...' : 'Generate Study Plan'}
          </Button>
        </Card>

        {/* Study Plan Display */}
        {(displayPlan.length > 0) && !studyMode && (
          <div className="plan-section animate-fade-in">
            <Card>
              <div className="plan-header-row">
                <h2 className="section-title">📅 Your Study Schedule</h2>
                <div className="header-buttons">
                  <button 
                    className="study-mode-btn"
                    onClick={() => {
                      const firstIncomplete = displayPlan.find(t => !t.completed)
                      const dayToStart = firstIncomplete ? firstIncomplete.day : 1
                      setCurrentStudyDay(dayToStart)
                      setStudyMode(true)
                    }}
                  >
                    📖 Start Study Mode
                  </button>
                  <button 
                    className={`google-cal-btn ${calendarStatus}`}
                    onClick={handleAutoSyncToCalendar}
                    disabled={calendarStatus === 'adding'}
                  >
                    {calendarStatus === 'adding' ? '📆 Opening Calendar...' :
                     calendarStatus === 'done' ? '✅ Tabs Opened!' :
                     '🗓️ Add to Google Calendar'}
                  </button>
                  <button 
                    className="download-cal-btn"
                    onClick={handleDownloadCalendar}
                    title="Download .ics file to import into any calendar app"
                  >
                    📥 Download .ics
                  </button>
                </div>
              </div>
              <div className="plan-grid">
                {displayPlan.map((task) => (
                  <div 
                    key={task.id} 
                    className={`plan-card priority-${task.priority} ${task.completed ? 'completed' : ''}`}
                  >
                    <div className="plan-header">
                      <span className="day-badge">Day {task.day}</span>
                      <span className={`priority-badge ${task.priority}`}>{task.priority}</span>
                    </div>
                    <div className="plan-topics">
                      {task.topics.join(', ')}
                    </div>
                    <div className="plan-duration">⏱️ {task.duration} minutes</div>
                    <div className="plan-date">
                      📅 {new Date(task.date).toLocaleDateString('en-US', { 
                        weekday: 'short',
                        month: 'short', 
                        day: 'numeric' 
                      })}
                    </div>
                    <div className="plan-actions">
                      <button 
                        className={`complete-btn ${task.completed ? 'is-completed' : ''}`}
                        onClick={() => handleToggleComplete(task.id, task.completed)}
                      >
                        {task.completed ? '✅ Completed' : '⬜ Mark Complete'}
                      </button>
                      <button 
                        className="add-cal-btn"
                        onClick={() => addToGoogleCalendar(task)}
                        title="Add to Calendar"
                      >
                        📆
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </Card>

            {/* Progress Overview */}
            <Card>
              <h2 className="section-title">📊 Progress Overview</h2>
              <div className="progress-bar-container">
                <div 
                  className="progress-bar-fill"
                  style={{ 
                    width: `${displayPlan.length > 0 ? Math.round((displayPlan.filter(t => t.completed).length / displayPlan.length) * 100) : 0}%` 
                  }}
                />
              </div>
              <div className="progress-stats">
                <div className="stat-item">
                  <div className="stat-value">{displayPlan.length}</div>
                  <div className="stat-label">Total Tasks</div>
                </div>
                <div className="stat-item completed-stat">
                  <div className="stat-value">{displayPlan.filter(t => t.completed).length}</div>
                  <div className="stat-label">Completed ✅</div>
                </div>
                <div className="stat-item remaining-stat">
                  <div className="stat-value">{displayPlan.filter(t => !t.completed).length}</div>
                  <div className="stat-label">Remaining 📝</div>
                </div>
                <div className="stat-item">
                  <div className="stat-value">
                    {displayPlan.length > 0 ? Math.round((displayPlan.filter(t => t.completed).length / displayPlan.length) * 100) : 0}%
                  </div>
                  <div className="stat-label">Progress</div>
                </div>
              </div>
            </Card>
          </div>
        )}

        {/* Study Mode UI */}
        {studyMode && displayPlan.length > 0 && (
          <div className="study-mode-container animate-fade-in">
            <Card>
              <div className="study-mode-header">
                <button 
                  className="exit-study-btn"
                  onClick={() => {
                    setStudyMode(false)
                    setStudyContent(null)
                    setStudyPhase('reading')
                  }}
                >
                  ← Exit Study Mode
                </button>
                <h2 className="study-mode-title">📖 Study Mode - Day {currentStudyDay}</h2>
                <div className="study-phase-indicator">
                  <span className={`phase-step ${studyPhase === 'reading' ? 'active' : (studyPhase === 'quiz' || studyPhase === 'complete') ? 'done' : ''}`}>1. Learn</span>
                  <span className="phase-arrow">→</span>
                  <span className={`phase-step ${studyPhase === 'quiz' ? 'active' : studyPhase === 'complete' ? 'done' : ''}`}>2. Quiz</span>
                  <span className="phase-arrow">→</span>
                  <span className={`phase-step ${studyPhase === 'complete' ? 'active' : ''}`}>3. Complete</span>
                </div>
              </div>

              {(() => {
                const currentTask = displayPlan.find(t => t.day === currentStudyDay)
                if (!currentTask) return <p>No task found for this day</p>

                // Already completed
                if (currentTask.completed) {
                  return (
                    <div className="already-completed">
                      <span className="completed-icon-big">🎉</span>
                      <h3>Day {currentTask.day} is already completed!</h3>
                      <p>Great job! You've already studied these topics.</p>
                      <div className="completed-actions">
                        <button 
                          className="nav-btn"
                          onClick={() => {
                            const nextIncomplete = displayPlan.find(t => !t.completed && t.day > currentStudyDay)
                            if (nextIncomplete) {
                              setCurrentStudyDay(nextIncomplete.day)
                              loadStudyContent(nextIncomplete.day)
                            }
                          }}
                        >
                          Go to Next Incomplete Day →
                        </button>
                        <button 
                          className="unmark-btn"
                          onClick={() => handleToggleComplete(currentTask.id, true)}
                        >
                          Re-study This Day
                        </button>
                      </div>
                    </div>
                  )
                }

                // Loading content
                if (loadingContent) {
                  return (
                    <div className="loading-content">
                      <div className="content-loader"></div>
                      <p>🤖 AI is preparing your study content...</p>
                      <p className="loading-subtitle">Generating explanations, examples, and quiz questions for:</p>
                      <div className="loading-topics">
                        {currentTask.topics.map((topic: string, idx: number) => (
                          <span key={idx} className="loading-topic">{topic}</span>
                        ))}
                      </div>
                    </div>
                  )
                }

                // No content loaded yet - show start button
                if (!studyContent) {
                  return (
                    <div className="start-study-prompt">
                      <div className="day-info">
                        <span className="study-day-badge">Day {currentTask.day}</span>
                        <span className={`study-priority-badge ${currentTask.priority}`}>{currentTask.priority} priority</span>
                      </div>
                      <h3>📚 Today's Topics</h3>
                      <div className="topics-preview">
                        {currentTask.topics.map((topic: string, idx: number) => (
                          <div key={idx} className="topic-preview-item">
                            <span className="topic-number">{idx + 1}</span>
                            <span>{topic}</span>
                          </div>
                        ))}
                      </div>
                      <p className="study-info">⏱️ Estimated time: {currentTask.duration} minutes</p>
                      <button 
                        className="start-learning-btn"
                        onClick={() => loadStudyContent(currentStudyDay)}
                      >
                        🚀 Start Learning
                      </button>
                    </div>
                  )
                }

                // Reading Phase - Show content
                if (studyPhase === 'reading') {
                  const currentTopic = studyContent.topics[currentTopicIndex]
                  return (
                    <div className="reading-phase">
                      <div className="topic-navigation">
                        <span className="topic-progress">Topic {currentTopicIndex + 1} of {studyContent.topics.length}</span>
                        <div className="topic-nav-buttons">
                          <button 
                            className="topic-nav-btn"
                            onClick={() => setCurrentTopicIndex(Math.max(0, currentTopicIndex - 1))}
                            disabled={currentTopicIndex === 0}
                          >
                            ← Previous
                          </button>
                          <button 
                            className="topic-nav-btn"
                            onClick={() => setCurrentTopicIndex(Math.min(studyContent.topics.length - 1, currentTopicIndex + 1))}
                            disabled={currentTopicIndex === studyContent.topics.length - 1}
                          >
                            Next →
                          </button>
                        </div>
                      </div>

                      <div className="content-card">
                        <h2 className="content-topic-title">📖 {currentTopic.name}</h2>
                        
                        <div className="content-section">
                          <h4>Explanation</h4>
                          <p className="explanation-text">{currentTopic.explanation}</p>
                        </div>

                        <div className="content-section">
                          <h4>🔑 Key Points</h4>
                          <ul className="key-points-list">
                            {currentTopic.keyPoints.map((point: string, idx: number) => (
                              <li key={idx}>{point}</li>
                            ))}
                          </ul>
                        </div>

                        <div className="content-section">
                          <h4>💡 Examples</h4>
                          <div className="examples-list">
                            {currentTopic.examples.map((example: string, idx: number) => (
                              <div key={idx} className="example-item">
                                <span className="example-icon">📌</span>
                                <span>{example}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>

                      {currentTopicIndex === studyContent.topics.length - 1 && (
                        <div className="reading-complete-actions">
                          <p>✅ You've read all topics! Ready to test your knowledge?</p>
                          <button 
                            className="start-quiz-btn"
                            onClick={() => setStudyPhase('quiz')}
                          >
                            📝 Take Quiz (3 Questions)
                          </button>
                        </div>
                      )}
                    </div>
                  )
                }

                // Quiz Phase
                if (studyPhase === 'quiz') {
                  return (
                    <div className="quiz-phase">
                      <h3 className="quiz-title">📝 Quick Quiz - Test Your Knowledge</h3>
                      <p className="quiz-subtitle">Answer all 3 questions correctly to complete Day {currentStudyDay}</p>

                      <div className="quiz-questions">
                        {studyContent.mcqs.map((mcq: any, qIdx: number) => (
                          <div key={qIdx} className={`quiz-question ${showQuizResults ? (quizAnswers[qIdx] === mcq.correctAnswer ? 'correct' : 'incorrect') : ''}`}>
                            <div className="question-header">
                              <span className="question-number">Q{qIdx + 1}</span>
                              <span className="question-text">{mcq.question}</span>
                            </div>
                            <div className="options-list">
                              {mcq.options.map((option: string, oIdx: number) => (
                                <button
                                  key={oIdx}
                                  className={`option-btn ${quizAnswers[qIdx] === oIdx ? 'selected' : ''} ${showQuizResults ? (oIdx === mcq.correctAnswer ? 'correct-answer' : quizAnswers[qIdx] === oIdx ? 'wrong-answer' : '') : ''}`}
                                  onClick={() => !showQuizResults && handleQuizAnswer(qIdx, oIdx)}
                                  disabled={showQuizResults}
                                >
                                  <span className="option-letter">{String.fromCharCode(65 + oIdx)}</span>
                                  <span className="option-text">{option}</span>
                                </button>
                              ))}
                            </div>
                            {showQuizResults && (
                              <div className="answer-explanation">
                                {quizAnswers[qIdx] === mcq.correctAnswer ? '✅ Correct!' : '❌ Incorrect'} - {mcq.explanation}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>

                      {!showQuizResults ? (
                        <button 
                          className="submit-quiz-btn"
                          onClick={handleSubmitQuiz}
                          disabled={quizAnswers.length < 3}
                        >
                          Submit Answers
                        </button>
                      ) : (
                        <div className="quiz-results">
                          <div className={`score-display ${quizScore === 3 ? 'perfect' : quizScore >= 2 ? 'good' : 'needs-work'}`}>
                            <span className="score-icon">{quizScore === 3 ? '🏆' : quizScore >= 2 ? '👍' : '📚'}</span>
                            <span className="score-text">{quizScore}/3 Correct</span>
                          </div>
                          
                          {quizScore === 3 ? (
                            <div className="perfect-score">
                              <p>🎉 Perfect Score! You're ready to complete this day!</p>
                              <button 
                                className="complete-day-btn"
                                onClick={() => handleCompleteDay(currentTask.id)}
                              >
                                ✅ Mark Day {currentStudyDay} as Complete
                              </button>
                            </div>
                          ) : (
                            <div className="retry-options">
                              <p>{quizScore >= 2 ? 'Good effort! Review the incorrect answers and try again.' : 'Keep practicing! Review the content and try the quiz again.'}</p>
                              <div className="retry-buttons">
                                <button 
                                  className="review-btn"
                                  onClick={() => {
                                    setStudyPhase('reading')
                                    setCurrentTopicIndex(0)
                                    setQuizAnswers([])
                                    setShowQuizResults(false)
                                  }}
                                >
                                  📖 Review Content
                                </button>
                                <button 
                                  className="retry-quiz-btn"
                                  onClick={() => {
                                    setQuizAnswers([])
                                    setShowQuizResults(false)
                                  }}
                                >
                                  🔄 Retry Quiz
                                </button>
                              </div>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  )
                }

                return null
              })()}

              {/* Progress dots */}
              <div className="study-progress-bar">
                <div className="progress-dots">
                  {displayPlan.map((task) => (
                    <div 
                      key={task.id}
                      className={`progress-dot ${task.completed ? 'completed' : ''} ${task.day === currentStudyDay ? 'current' : ''}`}
                      onClick={() => {
                        setCurrentStudyDay(task.day)
                        setStudyContent(null)
                        setStudyPhase('reading')
                        setCurrentTopicIndex(0)
                        setQuizAnswers([])
                        setShowQuizResults(false)
                      }}
                      title={`Day ${task.day}: ${task.topics.join(', ')}`}
                    >
                      {task.completed ? '✓' : task.day}
                    </div>
                  ))}
                </div>
              </div>
            </Card>
          </div>
        )}
      </div>

      <style jsx>{`
        .study-plan-page {
          max-width: 1000px;
          margin: 0 auto;
        }

        .page-title {
          font-size: var(--font-size-3xl);
          margin-bottom: var(--spacing-sm);
        }

        .page-subtitle {
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-2xl);
        }

        .section-title {
          font-size: var(--font-size-xl);
          font-weight: var(--font-weight-semibold);
          margin-bottom: var(--spacing-lg);
        }

        .form-group {
          margin-bottom: var(--spacing-lg);
        }

        .form-group label {
          display: block;
          font-weight: var(--font-weight-medium);
          margin-bottom: var(--spacing-sm);
          color: var(--color-text-primary);
        }

        .topic-input-wrapper {
          display: flex;
          gap: var(--spacing-sm);
        }

        .topic-input-wrapper .input {
          flex: 1;
        }

        .from-notes-btn {
          padding: var(--spacing-sm) var(--spacing-md);
          background: var(--color-accent-light);
          border: 2px solid var(--color-accent);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: var(--font-weight-medium);
          white-space: nowrap;
          transition: all var(--transition-fast);
        }

        .from-notes-btn:hover {
          background: var(--color-accent);
          color: white;
        }

        .concepts-picker {
          background: var(--color-bg-secondary);
          padding: var(--spacing-lg);
          border-radius: var(--radius-md);
          margin-bottom: var(--spacing-lg);
        }

        .picker-label {
          font-size: var(--font-size-sm);
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-md);
        }

        .concepts-grid {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-sm);
          margin-bottom: var(--spacing-md);
        }

        .concept-chip {
          padding: var(--spacing-xs) var(--spacing-md);
          background: white;
          border: 2px solid var(--color-border);
          border-radius: 20px;
          cursor: pointer;
          font-size: var(--font-size-sm);
          transition: all var(--transition-fast);
        }

        .concept-chip:hover {
          border-color: var(--color-accent);
        }

        .concept-chip.selected {
          background: var(--color-accent);
          border-color: var(--color-accent);
          color: white;
        }

        .form-row {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: var(--spacing-lg);
        }

        .plan-section {
          margin-top: var(--spacing-2xl);
          display: flex;
          flex-direction: column;
          gap: var(--spacing-lg);
        }

        .plan-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
          gap: var(--spacing-md);
        }

        .plan-card {
          padding: var(--spacing-lg);
          background: var(--color-bg-secondary);
          border-radius: var(--radius-md);
          border-left: 4px solid;
          transition: all var(--transition-fast);
        }

        .plan-card:hover {
          transform: translateY(-2px);
          box-shadow: var(--shadow-md);
        }

        .plan-card.priority-high {
          border-color: var(--color-error);
        }

        .plan-card.priority-medium {
          border-color: var(--color-warning);
        }

        .plan-card.priority-low {
          border-color: var(--color-info);
        }

        .plan-card.completed {
          opacity: 0.7;
          background: linear-gradient(135deg, #22c55e11 0%, #16a34a11 100%);
        }

        .plan-card.completed .plan-topics {
          text-decoration: line-through;
          color: var(--color-text-secondary);
        }

        .plan-header-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--spacing-lg);
          flex-wrap: wrap;
          gap: var(--spacing-md);
        }

        .calendar-btn {
          padding: var(--spacing-sm) var(--spacing-lg);
          background: linear-gradient(135deg, #4285f4 0%, #34a853 100%);
          color: white;
          border: none;
          border-radius: 25px;
          cursor: pointer;
          font-weight: 600;
          font-size: var(--font-size-sm);
          transition: all 0.3s ease;
          font-family: var(--font-body);
        }

        .calendar-btn:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 4px 15px rgba(66, 133, 244, 0.3);
        }

        .calendar-btn:disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }

        .plan-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--spacing-md);
        }

        .day-badge {
          font-weight: var(--font-weight-bold);
          color: var(--color-accent);
          font-size: var(--font-size-lg);
        }

        .priority-badge {
          padding: var(--spacing-xs) var(--spacing-sm);
          border-radius: var(--radius-full);
          font-size: var(--font-size-xs);
          font-weight: var(--font-weight-semibold);
          text-transform: uppercase;
        }

        .priority-badge.high {
          background: var(--color-error);
          color: white;
        }

        .priority-badge.medium {
          background: var(--color-warning);
          color: white;
        }

        .priority-badge.low {
          background: var(--color-info);
          color: white;
        }

        .plan-topics {
          font-weight: var(--font-weight-semibold);
          color: var(--color-text-primary);
          margin-bottom: var(--spacing-sm);
          font-size: var(--font-size-base);
        }

        .plan-duration {
          color: var(--color-text-secondary);
          font-size: var(--font-size-sm);
          margin-bottom: var(--spacing-xs);
        }

        .plan-date {
          color: var(--color-text-muted);
          font-size: var(--font-size-sm);
          margin-bottom: var(--spacing-md);
        }

        .plan-actions {
          display: flex;
          gap: var(--spacing-sm);
          margin-top: var(--spacing-sm);
          padding-top: var(--spacing-sm);
          border-top: 1px solid var(--color-border);
        }

        .complete-btn {
          flex: 1;
          padding: var(--spacing-sm);
          background: var(--color-bg-secondary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-size: var(--font-size-sm);
          font-weight: 600;
          transition: all 0.2s ease;
          font-family: var(--font-body);
        }

        .complete-btn:hover {
          border-color: #22c55e;
          background: #22c55e11;
        }

        .complete-btn.is-completed {
          background: #22c55e;
          border-color: #22c55e;
          color: white;
        }

        .add-cal-btn {
          padding: var(--spacing-sm) var(--spacing-md);
          background: var(--color-bg-secondary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-size: 18px;
          transition: all 0.2s ease;
        }

        .add-cal-btn:hover {
          border-color: #4285f4;
          background: #4285f411;
        }

        .progress-bar-container {
          height: 12px;
          background: var(--color-bg-secondary);
          border-radius: 10px;
          margin-bottom: var(--spacing-lg);
          overflow: hidden;
        }

        .progress-bar-fill {
          height: 100%;
          background: linear-gradient(90deg, #22c55e 0%, #16a34a 100%);
          border-radius: 10px;
          transition: width 0.5s ease;
        }

        .progress-stats {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
          gap: var(--spacing-lg);
        }

        .stat-item {
          text-align: center;
          padding: var(--spacing-lg);
          background: var(--color-bg-secondary);
          border-radius: var(--radius-md);
        }

        .stat-item.completed-stat {
          background: linear-gradient(135deg, #22c55e22 0%, #16a34a22 100%);
        }

        .stat-item.remaining-stat {
          background: linear-gradient(135deg, #f59e0b22 0%, #d9770622 100%);
        }

        .stat-value {
          font-size: var(--font-size-3xl);
          font-weight: var(--font-weight-bold);
          color: var(--color-accent);
          margin-bottom: var(--spacing-sm);
        }

        .stat-label {
          font-size: var(--font-size-base);
          color: var(--color-text-secondary);
        }

        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .animate-fade-in {
          animation: fadeIn 0.5s ease-out;
        }

        @media (max-width: 768px) {
          .form-row {
            grid-template-columns: 1fr;
          }
          .plan-header-row {
            flex-direction: column;
            align-items: stretch;
          }
          .calendar-btn {
            text-align: center;
          }
          .header-buttons {
            flex-direction: column;
          }
          .study-day-nav {
            flex-direction: column;
            gap: var(--spacing-sm);
          }
        }

        /* Header buttons */
        .header-buttons {
          display: flex;
          gap: var(--spacing-sm);
          flex-wrap: wrap;
        }

        .study-mode-btn {
          padding: var(--spacing-sm) var(--spacing-lg);
          background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .study-mode-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(99, 102, 241, 0.4);
        }

        .download-cal-btn {
          padding: var(--spacing-sm) var(--spacing-lg);
          background: linear-gradient(135deg, #10b981 0%, #059669 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .download-cal-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(16, 185, 129, 0.4);
        }

        /* Study Mode Styles */
        .study-mode-container {
          margin-top: var(--spacing-lg);
        }

        .study-mode-header {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-lg);
          margin-bottom: var(--spacing-xl);
          padding-bottom: var(--spacing-lg);
          border-bottom: 2px solid var(--color-border);
        }

        .exit-study-btn {
          align-self: flex-start;
          padding: var(--spacing-sm) var(--spacing-md);
          background: var(--color-bg-secondary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .exit-study-btn:hover {
          border-color: var(--color-accent);
          background: var(--color-bg-tertiary);
        }

        .study-mode-title {
          font-size: var(--font-size-2xl);
          font-weight: var(--font-weight-bold);
          text-align: center;
        }

        .study-day-nav {
          display: flex;
          justify-content: center;
          align-items: center;
          gap: var(--spacing-lg);
        }

        .nav-btn {
          padding: var(--spacing-sm) var(--spacing-lg);
          background: var(--color-bg-secondary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .nav-btn:hover:not(:disabled) {
          border-color: var(--color-accent);
          background: var(--color-accent);
          color: white;
        }

        .nav-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .current-day-label {
          font-size: var(--font-size-lg);
          font-weight: var(--font-weight-semibold);
          color: var(--color-accent);
        }

        .study-day-card {
          background: var(--color-bg-secondary);
          border-radius: var(--radius-lg);
          padding: var(--spacing-xl);
          margin-bottom: var(--spacing-xl);
        }

        .study-day-header {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-md);
          align-items: center;
          margin-bottom: var(--spacing-xl);
        }

        .study-day-badge {
          background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
          color: white;
          padding: var(--spacing-sm) var(--spacing-lg);
          border-radius: var(--radius-full);
          font-weight: var(--font-weight-bold);
          font-size: var(--font-size-lg);
        }

        .study-priority-badge {
          padding: var(--spacing-xs) var(--spacing-md);
          border-radius: var(--radius-full);
          font-size: var(--font-size-sm);
          font-weight: 600;
          text-transform: capitalize;
        }

        .study-priority-badge.high {
          background: #ef4444;
          color: white;
        }

        .study-priority-badge.medium {
          background: #f59e0b;
          color: white;
        }

        .study-priority-badge.low {
          background: #3b82f6;
          color: white;
        }

        .study-date {
          margin-left: auto;
          color: var(--color-text-secondary);
          font-size: var(--font-size-base);
        }

        .study-topics-section {
          margin-bottom: var(--spacing-xl);
        }

        .study-topics-section h3 {
          font-size: var(--font-size-lg);
          margin-bottom: var(--spacing-md);
        }

        .study-topics-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .study-topic-item {
          display: flex;
          align-items: center;
          gap: var(--spacing-md);
          padding: var(--spacing-md);
          background: var(--color-bg-primary);
          border-radius: var(--radius-md);
          border-left: 4px solid var(--color-accent);
        }

        .topic-number {
          width: 28px;
          height: 28px;
          background: var(--color-accent);
          color: white;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: bold;
          font-size: var(--font-size-sm);
        }

        .topic-name {
          font-size: var(--font-size-base);
          font-weight: 500;
        }

        .study-duration-section {
          display: flex;
          align-items: center;
          gap: var(--spacing-sm);
          padding: var(--spacing-md);
          background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%);
          border-radius: var(--radius-md);
          margin-bottom: var(--spacing-xl);
          color: #92400e;
        }

        .duration-icon {
          font-size: 24px;
        }

        .duration-text {
          font-size: var(--font-size-base);
        }

        .study-tips-section {
          margin-bottom: var(--spacing-xl);
          padding: var(--spacing-lg);
          background: linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%);
          border-radius: var(--radius-md);
        }

        .study-tips-section h4 {
          margin-bottom: var(--spacing-md);
          color: #1e40af;
        }

        .study-tips-list {
          list-style: none;
          padding: 0;
          margin: 0;
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .study-tips-list li {
          padding-left: var(--spacing-lg);
          position: relative;
          color: #1e40af;
          font-size: var(--font-size-sm);
        }

        .study-tips-list li::before {
          content: "→";
          position: absolute;
          left: 0;
          color: #3b82f6;
        }

        .study-actions {
          text-align: center;
          padding: var(--spacing-xl);
          background: var(--color-bg-primary);
          border-radius: var(--radius-lg);
        }

        .completed-message {
          color: #16a34a;
        }

        .completed-icon {
          font-size: 48px;
          display: block;
          margin-bottom: var(--spacing-md);
        }

        .completed-message h3 {
          font-size: var(--font-size-xl);
          margin-bottom: var(--spacing-sm);
        }

        .completed-message p {
          margin-bottom: var(--spacing-lg);
          color: var(--color-text-secondary);
        }

        .unmark-btn {
          padding: var(--spacing-sm) var(--spacing-lg);
          background: transparent;
          border: 2px solid #dc2626;
          color: #dc2626;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .unmark-btn:hover {
          background: #dc2626;
          color: white;
        }

        .study-prompt {
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-md);
        }

        .mark-complete-btn {
          padding: var(--spacing-md) var(--spacing-2xl);
          background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-size: var(--font-size-lg);
          font-weight: var(--font-weight-bold);
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .mark-complete-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(34, 197, 94, 0.4);
        }

        .study-progress-bar {
          padding: var(--spacing-lg);
          background: var(--color-bg-secondary);
          border-radius: var(--radius-lg);
        }

        .progress-dots {
          display: flex;
          justify-content: center;
          gap: var(--spacing-sm);
          flex-wrap: wrap;
        }

        .progress-dot {
          width: 36px;
          height: 36px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: var(--font-size-sm);
          font-weight: bold;
          cursor: pointer;
          transition: all 0.2s ease;
          background: var(--color-bg-primary);
          border: 2px solid var(--color-border);
        }

        .progress-dot:hover {
          transform: scale(1.1);
          border-color: var(--color-accent);
        }

        .progress-dot.current {
          border-color: var(--color-accent);
          background: var(--color-accent);
          color: white;
        }

        .progress-dot.completed {
          background: #22c55e;
          border-color: #22c55e;
          color: white;
        }

        .progress-dot.completed.current {
          box-shadow: 0 0 0 4px rgba(34, 197, 94, 0.3);
        }

        /* Google Calendar Button */
        .google-cal-btn {
          padding: var(--spacing-sm) var(--spacing-lg);
          background: linear-gradient(135deg, #4285f4 0%, #1a73e8 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .google-cal-btn:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(66, 133, 244, 0.4);
        }

        .google-cal-btn:disabled {
          opacity: 0.7;
          cursor: not-allowed;
        }

        .google-cal-btn.done {
          background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
        }

        .google-cal-btn.error {
          background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
        }

        /* Study Phase Indicator */
        .study-phase-indicator {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: var(--spacing-md);
          margin-top: var(--spacing-md);
        }

        .phase-step {
          padding: var(--spacing-xs) var(--spacing-md);
          border-radius: var(--radius-full);
          font-size: var(--font-size-sm);
          font-weight: 600;
          background: var(--color-bg-secondary);
          color: var(--color-text-muted);
          transition: all 0.3s ease;
        }

        .phase-step.active {
          background: var(--color-accent);
          color: white;
        }

        .phase-step.done {
          background: #22c55e;
          color: white;
        }

        .phase-arrow {
          color: var(--color-text-muted);
        }

        /* Loading Content */
        .loading-content {
          text-align: center;
          padding: var(--spacing-3xl);
        }

        .content-loader {
          width: 60px;
          height: 60px;
          margin: 0 auto var(--spacing-xl);
          border: 4px solid var(--color-border);
          border-top-color: var(--color-accent);
          border-radius: 50%;
          animation: spin 1s linear infinite;
        }

        @keyframes spin {
          to { transform: rotate(360deg); }
        }

        .loading-subtitle {
          color: var(--color-text-secondary);
          margin-top: var(--spacing-sm);
        }

        .loading-topics {
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          gap: var(--spacing-sm);
          margin-top: var(--spacing-lg);
        }

        .loading-topic {
          background: var(--color-bg-secondary);
          padding: var(--spacing-xs) var(--spacing-md);
          border-radius: var(--radius-full);
          font-size: var(--font-size-sm);
        }

        /* Start Study Prompt */
        .start-study-prompt {
          text-align: center;
          padding: var(--spacing-2xl);
        }

        .day-info {
          display: flex;
          justify-content: center;
          gap: var(--spacing-md);
          margin-bottom: var(--spacing-xl);
        }

        .topics-preview {
          max-width: 500px;
          margin: 0 auto var(--spacing-xl);
        }

        .topic-preview-item {
          display: flex;
          align-items: center;
          gap: var(--spacing-md);
          padding: var(--spacing-md);
          background: var(--color-bg-secondary);
          border-radius: var(--radius-md);
          margin-bottom: var(--spacing-sm);
          text-align: left;
        }

        .study-info {
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-xl);
        }

        .start-learning-btn {
          padding: var(--spacing-md) var(--spacing-3xl);
          background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
          color: white;
          border: none;
          border-radius: var(--radius-lg);
          cursor: pointer;
          font-size: var(--font-size-lg);
          font-weight: var(--font-weight-bold);
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .start-learning-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 20px rgba(99, 102, 241, 0.4);
        }

        /* Reading Phase */
        .reading-phase {
          padding: var(--spacing-lg);
        }

        .topic-navigation {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--spacing-xl);
          padding-bottom: var(--spacing-md);
          border-bottom: 1px solid var(--color-border);
        }

        .topic-progress {
          font-weight: 600;
          color: var(--color-accent);
        }

        .topic-nav-buttons {
          display: flex;
          gap: var(--spacing-sm);
        }

        .topic-nav-btn {
          padding: var(--spacing-xs) var(--spacing-md);
          background: var(--color-bg-secondary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .topic-nav-btn:hover:not(:disabled) {
          border-color: var(--color-accent);
          background: var(--color-accent);
          color: white;
        }

        .topic-nav-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .content-card {
          background: var(--color-bg-secondary);
          border-radius: var(--radius-lg);
          padding: var(--spacing-xl);
          margin-bottom: var(--spacing-xl);
        }

        .content-topic-title {
          font-size: var(--font-size-2xl);
          margin-bottom: var(--spacing-xl);
          color: var(--color-accent);
        }

        .content-section {
          margin-bottom: var(--spacing-xl);
        }

        .content-section h4 {
          font-size: var(--font-size-lg);
          margin-bottom: var(--spacing-md);
          color: var(--color-text-primary);
        }

        .explanation-text {
          line-height: 1.8;
          color: var(--color-text-secondary);
          font-size: var(--font-size-base);
        }

        .key-points-list {
          list-style: none;
          padding: 0;
        }

        .key-points-list li {
          padding: var(--spacing-sm) 0;
          padding-left: var(--spacing-lg);
          position: relative;
          color: var(--color-text-secondary);
        }

        .key-points-list li::before {
          content: "✓";
          position: absolute;
          left: 0;
          color: #22c55e;
          font-weight: bold;
        }

        .examples-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .example-item {
          display: flex;
          align-items: flex-start;
          gap: var(--spacing-sm);
          padding: var(--spacing-md);
          background: var(--color-bg-primary);
          border-radius: var(--radius-md);
          border-left: 3px solid #f59e0b;
        }

        .example-icon {
          flex-shrink: 0;
        }

        .reading-complete-actions {
          text-align: center;
          padding: var(--spacing-xl);
          background: linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%);
          border-radius: var(--radius-lg);
        }

        .reading-complete-actions p {
          color: #1e40af;
          margin-bottom: var(--spacing-md);
        }

        .start-quiz-btn {
          padding: var(--spacing-md) var(--spacing-2xl);
          background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-size: var(--font-size-lg);
          font-weight: var(--font-weight-bold);
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .start-quiz-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(139, 92, 246, 0.4);
        }

        /* Quiz Phase */
        .quiz-phase {
          padding: var(--spacing-lg);
        }

        .quiz-title {
          font-size: var(--font-size-xl);
          margin-bottom: var(--spacing-sm);
          text-align: center;
        }

        .quiz-subtitle {
          color: var(--color-text-secondary);
          text-align: center;
          margin-bottom: var(--spacing-xl);
        }

        .quiz-questions {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-xl);
        }

        .quiz-question {
          background: var(--color-bg-secondary);
          border-radius: var(--radius-lg);
          padding: var(--spacing-lg);
          border: 2px solid transparent;
          transition: all 0.3s ease;
        }

        .quiz-question.correct {
          border-color: #22c55e;
          background: rgba(34, 197, 94, 0.1);
        }

        .quiz-question.incorrect {
          border-color: #ef4444;
          background: rgba(239, 68, 68, 0.1);
        }

        .question-header {
          display: flex;
          gap: var(--spacing-md);
          margin-bottom: var(--spacing-md);
        }

        .question-number {
          width: 32px;
          height: 32px;
          background: var(--color-accent);
          color: white;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: bold;
          font-size: var(--font-size-sm);
          flex-shrink: 0;
        }

        .question-text {
          font-weight: 600;
          line-height: 1.5;
        }

        .options-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .option-btn {
          display: flex;
          align-items: center;
          gap: var(--spacing-md);
          padding: var(--spacing-md);
          background: var(--color-bg-primary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-family: var(--font-body);
          text-align: left;
          transition: all 0.2s ease;
        }

        .option-btn:hover:not(:disabled) {
          border-color: var(--color-accent);
        }

        .option-btn.selected {
          border-color: var(--color-accent);
          background: rgba(99, 102, 241, 0.1);
        }

        .option-btn.correct-answer {
          border-color: #22c55e;
          background: rgba(34, 197, 94, 0.2);
        }

        .option-btn.wrong-answer {
          border-color: #ef4444;
          background: rgba(239, 68, 68, 0.2);
        }

        .option-btn:disabled {
          cursor: default;
        }

        .option-letter {
          width: 28px;
          height: 28px;
          background: var(--color-bg-secondary);
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: bold;
          font-size: var(--font-size-sm);
          flex-shrink: 0;
        }

        .option-text {
          flex: 1;
        }

        .answer-explanation {
          margin-top: var(--spacing-md);
          padding: var(--spacing-md);
          background: var(--color-bg-primary);
          border-radius: var(--radius-md);
          font-size: var(--font-size-sm);
          color: var(--color-text-secondary);
        }

        .submit-quiz-btn {
          display: block;
          width: 100%;
          max-width: 300px;
          margin: var(--spacing-xl) auto 0;
          padding: var(--spacing-md);
          background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-size: var(--font-size-lg);
          font-weight: var(--font-weight-bold);
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .submit-quiz-btn:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(139, 92, 246, 0.4);
        }

        .submit-quiz-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .quiz-results {
          text-align: center;
          margin-top: var(--spacing-xl);
        }

        .score-display {
          display: inline-flex;
          align-items: center;
          gap: var(--spacing-md);
          padding: var(--spacing-lg) var(--spacing-2xl);
          border-radius: var(--radius-lg);
          margin-bottom: var(--spacing-xl);
        }

        .score-display.perfect {
          background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
          color: white;
        }

        .score-display.good {
          background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
          color: white;
        }

        .score-display.needs-work {
          background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
          color: white;
        }

        .score-icon {
          font-size: 32px;
        }

        .score-text {
          font-size: var(--font-size-xl);
          font-weight: var(--font-weight-bold);
        }

        .perfect-score p {
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-lg);
        }

        .complete-day-btn {
          padding: var(--spacing-md) var(--spacing-2xl);
          background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-size: var(--font-size-lg);
          font-weight: var(--font-weight-bold);
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .complete-day-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(34, 197, 94, 0.4);
        }

        .retry-options p {
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-lg);
        }

        .retry-buttons {
          display: flex;
          justify-content: center;
          gap: var(--spacing-md);
        }

        .review-btn {
          padding: var(--spacing-md) var(--spacing-xl);
          background: var(--color-bg-secondary);
          border: 2px solid var(--color-border);
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .review-btn:hover {
          border-color: var(--color-accent);
        }

        .retry-quiz-btn {
          padding: var(--spacing-md) var(--spacing-xl);
          background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
          color: white;
          border: none;
          border-radius: var(--radius-md);
          cursor: pointer;
          font-weight: 600;
          font-family: var(--font-body);
          transition: all 0.2s ease;
        }

        .retry-quiz-btn:hover {
          transform: translateY(-2px);
        }

        /* Already Completed */
        .already-completed {
          text-align: center;
          padding: var(--spacing-3xl);
        }

        .completed-icon-big {
          font-size: 64px;
          display: block;
          margin-bottom: var(--spacing-lg);
        }

        .already-completed h3 {
          font-size: var(--font-size-xl);
          margin-bottom: var(--spacing-sm);
          color: #22c55e;
        }

        .already-completed p {
          color: var(--color-text-secondary);
          margin-bottom: var(--spacing-xl);
        }

        .completed-actions {
          display: flex;
          justify-content: center;
          gap: var(--spacing-md);
          flex-wrap: wrap;
        }
      `}</style>
    </PageLayout>
  )
}
